name: iagno
version: 3.22.0
summary: 'Dominate the board in a classic version of Reversi'
description: |
  Iagno is a computer version of the game Reversi, a two-player strategy
  board game. The game is played with tiles that are dark on one side and
  light on the other.

  The object of Iagno is to flip as many of your opponent's tiles to your
  color as possible while preventing your opponent from flipping your tiles
  to his color. This is done by trapping your opponent's tiles between two
  tiles of your own color.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
    gnome-3-26-1604:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-26-1604

slots:
  # for GtkApplication registration
  iagno:
    interface: dbus
    bus: session
    name: org.gnome.iagno

apps:
  iagno:
    command: desktop-launch iagno
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - pulseaudio
      - unity7
      - wayland
    desktop: usr/share/applications/iagno.desktop

parts:
  iagno:
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: https://git.gnome.org/browse/iagno
    source-type: git
    source-tag: 3.22.0
    plugin: autotools
    prepare:
      sed -i.bak -e 's|=iagno$|=${SNAP}/meta/gui/iagno.png|g' data/iagno.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/iagno.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/iagno.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--disable-maintainer-mode, --prefix=/snap/iagno/current/usr]
    organize:
      snap/iagno/current/usr: usr
    build-packages:
      - appstream-util
      - gnome-pkg-tools
      - intltool
      - libcanberra-gtk3-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - valac
      - yelp-tools

